// <auto-generated />
using System;
using ApiVete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiVete.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20251205001434_TablasCompletas")]
    partial class TablasCompletas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiVete.Models.Cliente", b =>
                {
                    b.Property<int>("eCodCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eCodCliente"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iApellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("iCodEstatus")
                        .HasColumnType("int");

                    b.Property<string>("iDireccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iTelefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("eCodCliente");

                    b.ToTable("cat_clientes", (string)null);
                });

            modelBuilder.Entity("ApiVete.Models.Consulta", b =>
                {
                    b.Property<int>("eCodConsulta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eCodConsulta"));

                    b.Property<DateTime>("dFechaConsulta")
                        .HasColumnType("datetime2");

                    b.Property<int>("eCodMascota")
                        .HasColumnType("int");

                    b.Property<decimal>("iCosto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("iDiagnostico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iObservaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iSintomas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iTratamiento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("eCodConsulta");

                    b.ToTable("ret_consultas", (string)null);
                });

            modelBuilder.Entity("ApiVete.Models.Mascota", b =>
                {
                    b.Property<int>("eCodMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eCodMascota"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dFechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("eCodCliente")
                        .HasColumnType("int");

                    b.Property<string>("iAlergias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("iObservaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("iPeso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("iSexo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("eCodMascota");

                    b.ToTable("cat_mascotas", (string)null);
                });

            modelBuilder.Entity("ApiVete.Models.Producto", b =>
                {
                    b.Property<int>("eCodProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eCodProducto"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("iCodEstatus")
                        .HasColumnType("int");

                    b.Property<string>("iDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("iPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("iStock")
                        .HasColumnType("int");

                    b.HasKey("eCodProducto");

                    b.ToTable("cat_productos", (string)null);
                });

            modelBuilder.Entity("ApiVete.Models.Venta", b =>
                {
                    b.Property<int>("eCodVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eCodVenta"));

                    b.Property<DateTime>("dFechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("eCodCliente")
                        .HasColumnType("int");

                    b.Property<int>("eCodProducto")
                        .HasColumnType("int");

                    b.Property<int>("iCantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("iPrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("iTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("eCodVenta");

                    b.ToTable("cat_ventas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
